transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl {/home/merck/Projects/zet131/cores/vga/rtl/vga_write_iface.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl {/home/merck/Projects/zet131/cores/vga/rtl/vga_read_iface.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl {/home/merck/Projects/zet131/cores/vga/rtl/vga_cpu_mem_iface.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl {/home/merck/Projects/zet131/cores/vga/rtl/vga_config_iface.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl {/home/merck/Projects/zet131/cores/vga/rtl/vga_c4_iface.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl/fml {/home/merck/Projects/zet131/cores/vga/rtl/fml/vga_text_mode_fml.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl/fml {/home/merck/Projects/zet131/cores/vga/rtl/fml/vga_planar_fml.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl/fml {/home/merck/Projects/zet131/cores/vga/rtl/fml/vga_linear_fml.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl/fml {/home/merck/Projects/zet131/cores/vga/rtl/fml/vga_sequencer_fml.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl/fml {/home/merck/Projects/zet131/cores/vga/rtl/fml/vga_palette_regs_fml.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl/fml {/home/merck/Projects/zet131/cores/vga/rtl/fml/vga_pal_dac_fml.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl/fml {/home/merck/Projects/zet131/cores/vga/rtl/fml/vga_lcd_fml.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl/fml {/home/merck/Projects/zet131/cores/vga/rtl/fml/vga_fml.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl/fml {/home/merck/Projects/zet131/cores/vga/rtl/fml/vga_fifo.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl/fml {/home/merck/Projects/zet131/cores/vga/rtl/fml/vga_dac_regs_fml.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl/fml {/home/merck/Projects/zet131/cores/vga/rtl/fml/vga_crtc_fml.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/wb_switch {/home/merck/Projects/zet131/cores/wb_switch/wb_switch.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/flash {/home/merck/Projects/zet131/cores/flash/flash16.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/speaker/bare {/home/merck/Projects/zet131/cores/speaker/bare/speaker.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/serial/rtl {/home/merck/Projects/zet131/cores/serial/rtl/serial_atx.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/serial/rtl {/home/merck/Projects/zet131/cores/serial/rtl/serial_arx.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/serial/rtl {/home/merck/Projects/zet131/cores/serial/rtl/serial.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/timer/rtl {/home/merck/Projects/zet131/cores/timer/rtl/clk_gen.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/ps2/rtl {/home/merck/Projects/zet131/cores/ps2/rtl/ps2_mouse_nofifo.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/ps2/rtl {/home/merck/Projects/zet131/cores/ps2/rtl/ps2_mouse_datain.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/ps2/rtl {/home/merck/Projects/zet131/cores/ps2/rtl/ps2_mouse_cmdout.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/ps2/rtl {/home/merck/Projects/zet131/cores/ps2/rtl/ps2_mouse.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/ps2/rtl {/home/merck/Projects/zet131/cores/ps2/rtl/ps2_keyb.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/ps2/rtl {/home/merck/Projects/zet131/cores/ps2/rtl/ps2.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/sound/rtl {/home/merck/Projects/zet131/cores/sound/rtl/sound_dac8.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/sound/rtl {/home/merck/Projects/zet131/cores/sound/rtl/sound.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/boards/altera-de0/rtl {/home/merck/Projects/zet131/boards/altera-de0/rtl/kotku.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/boards/altera-de0/rtl {/home/merck/Projects/zet131/boards/altera-de0/rtl/pll.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/pic/rtl {/home/merck/Projects/zet131/cores/pic/rtl/simple_pic.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/gpio/rtl {/home/merck/Projects/zet131/cores/gpio/rtl/sw_leds.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/gpio/rtl {/home/merck/Projects/zet131/cores/gpio/rtl/hex_display.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/gpio/rtl {/home/merck/Projects/zet131/cores/gpio/rtl/seg_7.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/timer/rtl {/home/merck/Projects/zet131/cores/timer/rtl/timer.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/timer/rtl {/home/merck/Projects/zet131/cores/timer/rtl/timer_counter.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/wb_abrg {/home/merck/Projects/zet131/cores/wb_abrg/wb_abrgr.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl {/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl/hpdmc_sdrio.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl {/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl/hpdmc_banktimer.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl {/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl/hpdmc_busif.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl {/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl/hpdmc_ctlif.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl {/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl/hpdmc_datactl.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl {/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl/hpdmc_mgmt.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl {/home/merck/Projects/zet131/cores/hpdmc_sdr16/rtl/hpdmc.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/fmlarb/rtl {/home/merck/Projects/zet131/cores/fmlarb/rtl/fmlarb.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/fmlbrg/rtl {/home/merck/Projects/zet131/cores/fmlbrg/rtl/fmlbrg_datamem.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/fmlbrg/rtl {/home/merck/Projects/zet131/cores/fmlbrg/rtl/fmlbrg_tagmem.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/fmlbrg/rtl {/home/merck/Projects/zet131/cores/fmlbrg/rtl/fmlbrg.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/csrbrg/rtl {/home/merck/Projects/zet131/cores/csrbrg/rtl/csrbrg.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/wb_abrg {/home/merck/Projects/zet131/cores/wb_abrg/wb_abrg.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/sdspi/rtl {/home/merck/Projects/zet131/cores/sdspi/rtl/sdspi.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_wb_master.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_shrot.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_rxr16.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_rxr8.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_othop.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_nstate.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_next_or_not.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_mux8_16.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_mux8_1.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_muldiv.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_memory_regs.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_jmp_cond.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_fulladd16.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_div_uu.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_div_su.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_conv.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_bitlog.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_arlog.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_alu.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_addsub.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl/altera {/home/merck/Projects/zet131/cores/zet/rtl/altera/zet_signmul17.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/defines.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/rom_def.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/vga/rtl {/home/merck/Projects/zet131/cores/vga/rtl/vga_char_rom.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/flash {/home/merck/Projects/zet131/cores/flash/bootrom.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/ps2/rtl {/home/merck/Projects/zet131/cores/ps2/rtl/ps2_keyb_xtcodes.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_regfile.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_opcode_deco.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_micro_rom.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_micro_data.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_fetch.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_exec.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_decode.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet_core.v}
vlog -vlog01compat -work work +incdir+/home/merck/Projects/zet131/cores/zet/rtl {/home/merck/Projects/zet131/cores/zet/rtl/zet.v}

